# Generated by Django 2.2.28 on 2023-03-10 16:44

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='registered_players',
        ),
        migrations.AddField(
            model_name='player',
            name='registered_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manager.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='/home/kiwi/Documents/University/Computer Science/WAD/9E_WAD_GROUP/WAD_Code/static/images/default_profile.jpeg', upload_to=manager.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Team_Players',
        ),
    ]
