# Generated by Django 2.2.28 on 2023-03-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20230310_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='gallery',
            field=models.CharField(default='team_gallery/team_<django.db.models.fields.CharField>/', max_length=200),
        ),
    ]
