# Generated by Django 2.2.28 on 2023-03-16 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_auto_20230310_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('is_a_captain', 'Standard Captain Permissions'), ('is_a_player', 'Standard Player Permissions'))},
        ),
        migrations.RemoveField(
            model_name='player',
            name='forename',
        ),
        migrations.RemoveField(
            model_name='player',
            name='surname',
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='0', unique=True),
        ),
    ]
