# Generated by Django 2.2.28 on 2023-03-13 00:45

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20230310_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_pic',
            field=models.ImageField(default='C:\\Users\\Henry\\OneDrive\\Desktop\\wad2\\project\\9E_WAD_GROUP\\WAD_Code\\static/images/default_profile.jpeg', upload_to=manager.models.user_directory_path),
        ),
    ]
