# Generated by Django 2.2.28 on 2023-03-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20230313_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('is_a_captain', 'Standard Captain Permissions'), ('is_a_player', 'Standard Player Permissions'))},
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
