# Generated by Django 2.2.28 on 2023-03-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20230316_1703'),
        ('manager', '0005_auto_20230313_1631'),
    ]

    operations = [
    ]
