# Generated by Django 2.2.28 on 2023-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20230316_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='error', unique=True),
        ),
    ]
