# Generated by Django 2.2.28 on 2023-03-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20230320_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(blank=True),
        ),
    ]
