# Generated by Django 2.2.28 on 2023-03-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20230320_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.IntegerField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(blank=True, default='-'),
        ),
    ]
