# Generated by Django 2.2.28 on 2023-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20230320_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
