# Generated by Django 2.2.28 on 2023-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20230320_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_password',
            field=models.CharField(default='defaultPassword', max_length=32),
        ),
    ]
